version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      # - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.15.0
    restart: always
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.15.0
    ports:
      - 5046:5046
    volumes:
     - ./_elk/logstash_configs/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
     - ./_elk/logstash_configs/pipelines:/usr/share/logstash/config/pipelines:ro
     - ./_elk/input_data:/usr/share/logstash/input_data


volumes:
  elasticsearch:
    driver: local